### ISSUE TITLE
I have erros

### ISSUE THREAD

**Issue by jhanc97** [libDrive/libDrive#1]
Hello, I have errors, could you help me to implement it correctly please
![Windowshot_2021-02-01_17:24:21](https://user-images.githubusercontent.com/73450591/106525881-aaf3e900-64b2-11eb-850a-c776cb661dcc.png)
![Windowshot_2021-02-01_17_27_05](https://user-images.githubusercontent.com/73450591/106526153-1ccc3280-64b3-11eb-9670-d4e995300045.jpg)

**Comment by eliasbenb** [comment]
I need to know the following:
- Are you using the latest version of libDrive (if not please try the latest version)?
- Are you deploying to Heroku?

If the answer to both of those is yes, then I believe the problem lies in the config.

**Comment by jhanc97** [comment]
@eliasbenb If I am using the latest version, I am deploying it on a local pc.

**Comment by eliasbenb** [comment]
Are your files stored on a personal Google Drive? So **not** a team drive?

If so, I've never tested the app on a personal drive, so I might need to fix that soon.

**Comment by jhanc97** [comment]
@eliasbenb I first tried on a team drive the same error occurs also ...

**Comment by jhanc97** [comment]
@eliasbenb A query, I recognize the "team drive id".  But what is the "folder id"? 
![Screenshot_20210206_115134](https://user-images.githubusercontent.com/73450591/107124470-14d50f80-6872-11eb-96ca-06ec85c3def0.jpg)

**Comment by eliasbenb** [comment]
> @eliasbenb A query, I recognize the "team drive id". But what is the "folder id"?
> ![Screenshot_20210206_115134](https://user-images.githubusercontent.com/73450591/107124470-14d50f80-6872-11eb-96ca-06ec85c3def0.jpg)

I'm going to document this in the README later, but the folder_id is the ID for a specific folder, you can get it from the end of the URL when you open the folder in your browser.

If the source isn't a folder, but the actual drive, then the folder ID is the team drive ID (or `root` if you are using a personal drive)

If you are using a personal drive, then you can leave the team drive ID empty

**Comment by jhanc97** [comment]
Well when I'm free I'll try it again and he told her ...

**Comment by eliasbenb** [comment]
Ok, I'm pretty sure I understand what's happening.

The logs are saying that category['children'] (which is where the files for a drive is stored) is empty, so it can't continue (I will add a barrier to prevent this happening)

This could mean 2 things:
1. The folder is actually empty
2. Or you somehow put the wrong information in the config's `category_list` field

This is what it should look like for a personal drive (you can copy this exactly): `category_list = [{"type":"Movies","name":"Movies","id":"root","driveId":""}]`

For a team drive: `category_list = [{"type":"Movies","name":"Movies","id":"xxxxxxxxxxxxxx","xxxxxxxxxxxxxxxxxxxxx":""}]`
put the actual values in

**Comment by jhanc97** [comment]
@eliasbenb Ok thanks

**Comment by eliasbenb** [comment]
After further investigation, I've found another, more likely, possibility: the folder does contain files, but they are non video files, so the app recognizes that there are files, but can't process them.

I plan on fixing this soon. Thank you for raising this issue.

**Comment by eliasbenb** [comment]
> After further investigation, I've found another, more likely, possibility: the folder does contain files, but they are non video files, so the app recognizes that there are files, but can't process them.
> 
> I plan on fixing this soon. Thank you for raising this issue.

Assuming the issue came from this scenario, I've fixed the problem. Please clone the app again to get the updates
<https://github.com/libDrive/backend/commit/ed9e54194cd4febe419ed77ad4f2c80ba7cce121>

**Comment by mohitjoshi155** [comment]
![Screenshot_20210207-114107_Browser](https://user-images.githubusercontent.com/58655292/107138282-9f347680-6939-11eb-819f-119ebc425fc6.jpg)
Do u need some kind of approval from tmdb coz in my case it just keeps loading

**Comment by eliasbenb** [comment]
> ![Screenshot_20210207-114107_Browser](https://user-images.githubusercontent.com/58655292/107138282-9f347680-6939-11eb-819f-119ebc425fc6.jpg)
> Do u need some kind of approval from tmdb coz in my case it just keeps loading

The fix wasn't updated for Heroku yet. Just for local deployment.
I've just updated it now.
<https://github.com/libDrive/heroku/commit/b62d3bfed8de2bd7d46936a0f5a4636f31807771>

Try redeploying to see if the issue still persists

**Comment by mohitjoshi155** [comment]
[libdrive155-logs-1612700068509.txt](https://github.com/libDrive/libDrive/files/5938957/libdrive155-logs-1612700068509.txt)
Still same problem but logs chgd...have a look

**Comment by eliasbenb** [comment]
> [libdrive155-logs-1612700068509.txt](https://github.com/libDrive/libDrive/files/5938957/libdrive155-logs-1612700068509.txt)
> Still same problem but logs chgd...have a look

Please look at the below message I previously sent. Make sure the category_list is correct.

> This is what it should look like for a personal drive (you can copy this exactly): `category_list = [{"type":"Movies","name":"Movies","id":"root","driveId":""}]`
> 
> For a team drive: `category_list = [{"type":"Movies","name":"Movies","id":"xxxxxxxxxxxx","driveId":"xxxxxxxxxxxx"}]`
> put the actual values in

**Comment by mohitjoshi155** [comment]
> > [libdrive155-logs-1612700068509.txt](https://github.com/libDrive/libDrive/files/5938957/libdrive155-logs-1612700068509.txt)
> > Still same problem but logs chgd...have a look
> 
> Please look at the below message I previously sent. Make sure the category_list is correct.
> 
> > This is what it should look like for a personal drive (you can copy this exactly): `category_list = [{"type":"Movies","name":"Movies","id":"root","driveId":""}]`
> > For a team drive: `category_list = [{"type":"Movies","name":"Movies","id":"xxxxxxxxxxxx","driveId":"xxxxxxxxxxxx"}]`
> > put the actual values in

For id If I put folder id and for drive id I put teamdrive id then it should show contents inside folder of that team drive right?

**Comment by mohitjoshi155** [comment]
> Well when I'm free I'll try it again and he told her ...

Lemme know how u solved it coz I get the same logs as urs on heroku

**Comment by jhanc97** [comment]
@eliasbenb I managed to make it recognize some series "not all" ... but at the time of playing it sends me an error of the daily limit exceeded.
![Windowshot_2021-02-07_14:28:20](https://user-images.githubusercontent.com/73450591/107157256-19242a00-6951-11eb-8fe0-541bb755d6e8.png)
![Windowshot_2021-02-07_14:27:28](https://user-images.githubusercontent.com/73450591/107157257-1a555700-6951-11eb-9e03-b7fb4bf2c29a.png)
![Windowshot_2021-02-07_14:27:07](https://user-images.githubusercontent.com/73450591/107157258-1aeded80-6951-11eb-9dc6-70495339ae73.png)

**Comment by jhanc97** [comment]
It would be great if in the "readme" file you put the folder hierarchy so that it correctly recognizes the media. For example series: "The Crown (2016) / Season 01 / Capitulo 1 / the crown S01E1-first episode.mp4, mkv, etc."

**Comment by eliasbenb** [comment]
> It would be great if in the "readme" file you put the folder hierarchy so that it correctly recognizes the media. For example Tv shows: "The Crown (2016) / Season 01 / Episode 1 / the crown S01E1-first episode.mp4, mkv, etc."

I've just added a Wiki
<https://github.com/libDrive/libDrive/wiki/Structure>
