### ISSUE TITLE
Deployed on Heroku - Keeps asking me if this is the correct backend

### ISSUE THREAD

**Issue by bnichs5** [libDrive/libDrive#11]
Hello.

I deployed this on heroku, did the configuration and put the code in. When i try to log in i can see the tv shows but when i click on one, it tells me "Something went wrong while communicating with the backend! Is 'https://XXXXXX.herokuapp.com' the correct address?" Retry or Logout. wont let me past here.

Any help would be greatly appreciated!

**Comment by eliasbenb** [comment]
Fill out the forum provided in the bug report template.
