### ISSUE TITLE
Shared drive support

### ISSUE THREAD

**Issue by telegrambotdev** [libDrive/libDrive#13]
can you please add shared drive support ? right now its not working.

**Comment by dishapatel010** [comment]
its working make sure your structure of shared drive 

for more see wiki : [structure](https://github.com/libDrive/libDrive/wiki/Structure)

**Comment by dishapatel010** [comment]
> its working make sure your structure of shared drive
> 
> for more see wiki : [structure](https://github.com/libDrive/libDrive/wiki/Structure)

if you want to see example just DM me on telegram [Empathiz](telegram.dog/empathiz)

**Comment by telegrambotdev** [comment]
> its working make sure your structure of shared drive
> 
> for more see wiki : [structure](https://github.com/libDrive/libDrive/wiki/Structure)
> 
> if you want to see example just DM me on telegram [Empathiz](https://telegram.dog/empathiz)

check telegram,i texted there

**Comment by eliasbenb** [comment]
Shared drives definitely work. To point to a team drive folder in the `category_list` config item, set the `id` field to the folder ID, you can get it from the last part of the URL when you open the folder in a browser
