### ISSUE TITLE
[ENHANCEMENT]

### ISSUE THREAD

**Issue by dishapatel010** [libDrive/libDrive#14]
### Outline of feature request
1. 404 page & its redirect to homepage
2. Redirect Unauth - Check if user is login 1st or not if not then redirect to /login
3. Instead of TMDb api if we make poster inside the same folder of content then to fetch it for use
4. Notification / Announcement Page

### Reason
1. ![404 page](https://user-images.githubusercontent.com/71930916/116414358-05080e80-a856-11eb-8005-46419680a405.png)

if you try to request with/out sign in to your website 

> example.com/xyz

 it will show blank screen. so therefore we need 404 page.

2. ![Redirect Unauth](https://user-images.githubusercontent.com/71930916/116415209-d63e6800-a856-11eb-8518-9def6b0c831b.png)

if any you try to open any url of your content without signing in ```auth= true``` condition then it will ultimately buffer. 

> example.com/view/1c6rnJgFFncbCM5TPPwMing4AmbEsHxfO

so therefore we need to check at request if it is signed or nor if not then to redirect to /login page.

3. its simple just add image of poster in folder as the respective name of content eg. ```binod.png``` for ```Binod movie```
[i thinks this will make complicated so we can skip this one lol!]

4.   A custom page for users to ```get to know``` what new has been added to website / Notification - for upcoming content.

**Comment by eliasbenb** [comment]
I'll split my comment into sections based on the ideas:

404 page: great idea, should be really easy to do

Redirect unauthed: also a good idea, I actually thought I fixed it, but I realize there's some holes in the logic I used, but I should be able to fix it

Local posters: this is similar to another idea from issue #10 , for the same reason, I'll decline

Notification/announcements: I think it's a great idea, but it could be annoying for some users to see notifications, also I'd need to setup an RSS feed and maintain it

**Comment by dishapatel010** [comment]
> I'll split my comment into sections based on the ideas:
> 
> 404 page: great idea, should be really easy to do
> 
> Redirect unauthed: also a good idea, I actually thought I fixed it, but I realize there's some holes in the logic I used, but I should be able to fix it
> 
> Local posters: this is similar to another idea from issue #10 , for the same reason, I'll decline
> 
> Notification/announcements: I think it's a great idea, but it could be annoying for some users to see notifications, also I'd need to setup an RSS feed and maintain it



> I'll split my comment into sections based on the ideas:
> 
> 404 page: great idea, should be really easy to do
> 
> Redirect unauthed: also a good idea, I actually thought I fixed it, but I realize there's some holes in the logic I used, but I should be able to fix it
> 
> Local posters: this is similar to another idea from issue #10 , for the same reason, I'll decline
> 
> Notification/announcements: I think it's a great idea, but it could be annoying for some users to see notifications, also I'd need to setup an RSS feed and maintain it

okay then wait.......

**Comment by eliasbenb** [comment]
The 404 page and auth check have been implemented

https://github.com/libDrive/web/commit/f47163a95d1ed21d3125fcfcaa5c98343a385f28
https://github.com/libDrive/web/commit/28ed1355d57040f31ee49a76b08ec94720e18a0a

Expect it in the next update.

**Comment by eliasbenb** [comment]
Screenshot of the 404 page

![localhost_3000_api_v1_metadata](https://user-images.githubusercontent.com/54410649/116550547-fa0db680-a907-11eb-9eca-ce6facc5e079.png)

**Comment by dishapatel010** [comment]
> Screenshot of the 404 page
> 
> ![localhost_3000_api_v1_metadata](https://user-images.githubusercontent.com/54410649/116550547-fa0db680-a907-11eb-9eca-ce6facc5e079.png)

Nice!!!

**Comment by eliasbenb** [comment]
I made a simple announcement page which just displays the 3 latest releases using the GitHub API

![image](https://user-images.githubusercontent.com/54410649/117056055-efe72000-ad2c-11eb-8280-8427cf7087f1.png)

commit: https://github.com/libDrive/web/commit/789a09c07fcac74f8a47b68063d8e5f375abccd7

**Comment by eliasbenb** [comment]
I'll close the issue now.
