### ISSUE TITLE
A Suggestion .

### ISSUE THREAD

**Issue by ronin08** [libDrive/libDrive#16]
Hey ! thanks for this media server :) 

I found the transcoded feature in the streaming very useful . Can you please send me that particular code for using transcoding . Or can you help me to implement that in plyr.io stream . 

It would be great if transcoded option is added in this one ( https://github.com/ParveenBhadooOfficial/Google-Drive-Index) an awesome G-Drive Indexer . It uses Cloudfare Worker Script solely and plyr.io for streaming .

Another idea is that you can colab with him to make an overall impressive Google Drive Media-Server ! 

Cheers ! 

Please tell your thoughts !

**Comment by eliasbenb** [comment]
I'm not interested in contributing, but I'll provide the location of the code

https://github.com/libDrive/server/blob/main/main.py#L681-L710
https://github.com/libDrive/cloudflare/blob/main/index.js#L25-L42

Please don't follow this up with questions.
