### ISSUE TITLE
[ENHANCEMENT] Is it possible to specify movie poster size?

### ISSUE THREAD

**Issue by Ghazni1337** [libDrive/libDrive#17]
Is it possible to specify movie poster size?

Because it's showing a too large poster than the original video player size. It seems a bit annoying.

**Comment by eliasbenb** [comment]
I agree, the poster on smaller screens for the movie page was pretty useless.
I've just removed it (only for smaller screens on the movie page).

I feel like a config option for the poster size was too much for such a small issue.
Hopefully this fix is what you wanted.

Screenshot:
![screen](https://user-images.githubusercontent.com/54410649/120889641-24d9e180-c60f-11eb-87fa-aa3cb9efd789.png)

**Comment by eliasbenb** [comment]
I'll close the issue, if you have a follow up feel free to reopen it.
