### ISSUE TITLE
[ENHANCEMENT] Change information language, and group movies in different quality.

### ISSUE THREAD

**Issue by mauricio551** [libDrive/libDrive#18]
### Outline of feature request

Is there a way to create an env bar or something similar to change the language of the information of the movies and series, I mean the screen where the description appears, etc. I also wish that when it detects a repeated film, it groups it into a single one and allows me to choose between them, since if there is a film in different qualities, it will leave them separate and it will be very bad, I attached a screenshot of this at the end.
### Reason

My native language is not English so I would like an option to change this. With regard to grouping a film that is in different qualities into one, I would like that because it just looks bad, but it is not completely necessary.

**Additional information**
When I say description screen I mean the following screenshot, I would like to change the language of the synopsis, etc. 

![Screenshot_20210601-213117~2](https://user-images.githubusercontent.com/82117562/120420424-8ead6f00-c321-11eb-8630-a685acb75730.png)

This screenshot is about not grouping a movie that is in different qualities into one.

![Screenshot_20210601-213300](https://user-images.githubusercontent.com/82117562/120420425-8fde9c00-c321-11eb-9e78-77081be9fc99.png)

**Comment by eliasbenb** [comment]
Great suggestions!

# Languages

For the first suggestion (the languages one), it was pretty simple to implement.
You can find the updated code in this commit https://github.com/libDrive/server/commit/1ae73c36e04294d35d59303b54e5d0b42bc6de45

To set the language, you need to find the correct [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) code for your language as outlined in the [TMDB API docs](https://developers.themoviedb.org/3/getting-started/languages). After finding the correct ISO 639-1 code, create a new field named `language` under a category you want to use a custom language with, then set it to the ISO 639-1 code.

Example:
```
"category_list": [
    {
        "id": "xxxxxxxxxxxxxxxxxx",
        "name": "xxxxxxxxx",
        "type": "Movies",
        "language": "en"
    }
],
```

# Grouping qualities

This suggestion is a lot tougher, many other users have requested this, I'm working on getting it implemented, but no promises!

Thank you again for the suggestions.

**Comment by mauricio551** [comment]
Thank you very much, if I have it in heroku, should I wait for a new "release" to come out or is it automatically updated? I have the in var set to "latest" I say it to start setting the language.

**Comment by eliasbenb** [comment]
> Thank you very much, if I have it in heroku, should I wait for a new "release" to come out or is it automatically updated? I have the env var set to "latest" I say it to start setting the language.

wait for a new release
