### ISSUE TITLE
[ENHANCEMENT] Inlcude subtitles found in location of media

### ISSUE THREAD

**Issue by atmos-o** [libDrive/libDrive#19]
A lot of us have separate subtitle files in the same folder location. If libDrive could add that in along with the player it would be really useful. 
I personally have my sub files named the same as the media with the language code included, like this "`TheMovie`.`en`.vtt" or for shows "`Show Name` `S01E02`.`en`.vtt"

I'm not sure how it's currently enabled, but I think I read here that its pulled from the video file if a sub track is included maybe? Would supporting `.srt` files be possible? If not people can convert it to `.vtt` with a short ffmpeg command in a few seconds. I already have all mine in `.vtt` but it's just one less step for new comers.

**Comment by eliasbenb** [comment]
Great suggestion!

This was quite a hard one, but I've got an alpha version working, I'll need to test it out more though.
You can see the updated code in these commits:

- https://github.com/libDrive/server/commit/0d2034aeba661b346794bbdac8fda674fd17572d
- https://github.com/libDrive/web/commit/fa6508a1b722ab4c62cfdcbac5ac21b7eff4c2c8

In the current commit, srt files won't work, only vtt, but I'm trying to get it working for srt too.

So, the requirements of the subtitle are the following:

- The subtitle is in the same folder as the video
- The subtitle is in the WebVTT format
- The `subtitles` config option must be set to `true`

**Comment by dishapatel010** [comment]
> Great suggestion!
> 
> This was quite a hard one, but I've got an alpha version working, I'll need to test it out more though.
> You can see the updated code in these commits:
> 
> * [libDrive/server@0d2034a](https://github.com/libDrive/server/commit/0d2034aeba661b346794bbdac8fda674fd17572d)
> * [libDrive/web@fa6508a](https://github.com/libDrive/web/commit/fa6508a1b722ab4c62cfdcbac5ac21b7eff4c2c8)
> 
> In the current commit, srt files won't work, only vtt, but I'm trying to get it working for srt too.
> 
> So, the requirements of the subtitle are the following:
> 
> * The subtitle is in the same folder as the video
> * The subtitle is in the WebVTT format
> * The `subtitles` config option must be set to `true`

Cool lets try out!

**Comment by eliasbenb** [comment]
I'll close the issue, if you have a follow up feel free to reopen it.
