### ISSUE TITLE
Heroku Error

### ISSUE THREAD

**Issue by aditya-shri** [libDrive/libDrive#2]
Deployed just fine but when tried to visit the server, it crashed.
![Screenshot](https://user-images.githubusercontent.com/18643014/106951505-dba77d00-6755-11eb-9cea-9377ea347387.jpg)

**Comment by eliasbenb** [comment]
Could you try restarting the app and send me the logs, because these logs seem incomplete, the app (main.py) hasn't even started, the errors are coming from [Gunicorn](https://gunicorn.org/) which is what serves the app

To restart click `More` near the top right of the Heroku dashboard and select `Restart all dynos`

**Comment by aditya-shri** [comment]
Here are the logs which also contains the point of error in it.
[logs.txt](https://github.com/libDrive/libDrive/files/5937520/logs.txt)

**Comment by eliasbenb** [comment]
After reviewing the logs, this was the point of error
```
2021-02-06T19:38:05.377298+00:00 app[web.1]: File "/app/main.py", line 37, in <module>
2021-02-06T19:38:05.377299+00:00 app[web.1]: metadata = src.metadata.writeMetadata(
2021-02-06T19:38:05.377299+00:00 app[web.1]: File "/app/src/metadata.py", line 172, in writeMetadata
2021-02-06T19:38:05.377299+00:00 app[web.1]: "tmdbId"] = item["name"][:-len(item["fullFileExtention"])], "", "", "1900-01-01", ""
2021-02-06T19:38:05.377300+00:00 app[web.1]: KeyError: 'fullFileExtention'
```

I believe I fixed the issue. You need to manually update your local repository, or if on Heroku redeploy
https://github.com/libDrive/backend/commit/889ca8ea0c2f1a3d672b3210cfcb14ba85fcd8f5

**Comment by leonard4546** [comment]
> After reviewing the logs, this was the point of error
> 
> ```
> 2021-02-06T19:38:05.377298+00:00 app[web.1]: File "/app/main.py", line 37, in <module>
> 2021-02-06T19:38:05.377299+00:00 app[web.1]: metadata = src.metadata.writeMetadata(
> 2021-02-06T19:38:05.377299+00:00 app[web.1]: File "/app/src/metadata.py", line 172, in writeMetadata
> 2021-02-06T19:38:05.377299+00:00 app[web.1]: "tmdbId"] = item["name"][:-len(item["fullFileExtention"])], "", "", "1900-01-01", ""
> 2021-02-06T19:38:05.377300+00:00 app[web.1]: KeyError: 'fullFileExtention'
> ```
> 
> I believe I fixed the issue. You need to manually redeploy the Heroku repository
> [libDrive/backend@889ca8e](https://github.com/libDrive/backend/commit/889ca8ea0c2f1a3d672b3210cfcb14ba85fcd8f5)

[sastaflix-logs-1612725514011.txt](https://github.com/libDrive/libDrive/files/5939797/sastaflix-logs-1612725514011.txt)

hey I'm facing this issue. Deployed using button.

**Comment by eliasbenb** [comment]
> [sastaflix-logs-1612725514011.txt](https://github.com/libDrive/libDrive/files/5939797/sastaflix-logs-1612725514011.txt)
> 
> hey I'm facing this issue. Deployed using button. 

You either don't have a TMDB API key or have an incorrect TMDB API key in your config.

Your issue is unrelated the to this topic's issue. If you have more questions, please start a new issue.

Further replies on this issue will not be answered.

**Comment by aditya-shri** [comment]
The issue still exist.
I redeployed

**Comment by eliasbenb** [comment]
> The issue still exist.
> I redeployed

Can you send the new logs please.

**Comment by eliasbenb** [comment]
@aditya-shri 
I was able to reproduce your error and believe I have fixed it. Please try redeploying the latest update. Thank you for your pateince.
<https://github.com/libDrive/backend/commit/e26bf9c4058f1941f78396dee11821355e5dda69>

**Comment by aditya-shri** [comment]
Now a new error is happening after login.
[logs.txt](https://github.com/libDrive/libDrive/files/5943774/logs.txt)

I'm using apiv3 of tmdb

**Comment by ronioncloud** [comment]
> Deployed just fine but when tried to visit the server, it crashed.
> ![Screenshot](https://user-images.githubusercontent.com/18643014/106951505-dba77d00-6755-11eb-9cea-9377ea347387.jpg)

Same error :(

"2021-02-10T18:50:37.548981+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/configparser.py", line 1254, in __getitem__
2021-02-10T18:50:37.548981+00:00 app[web.1]:     raise KeyError(key)
2021-02-10T18:50:37.548981+00:00 app[web.1]: KeyError: 'cloudflare'
2021-02-10T18:50:37.549145+00:00 app[web.1]: [2021-02-10 18:50:37 +0000] [7] [INFO] Worker exiting (pid: 7)
2021-02-10T18:50:37.715928+00:00 app[web.1]: [2021-02-10 18:50:37 +0000] [4] [INFO] Shutting down: Master
2021-02-10T18:50:37.716038+00:00 app[web.1]: [2021-02-10 18:50:37 +0000] [4] [INFO] Reason: Worker failed to boot.
2021-02-10T18:50:37.785035+00:00 heroku[web.1]: Process exited with status 3
2021-02-10T18:50:37.869776+00:00 heroku[web.1]: State changed from up to crashed
2021-02-10T18:50:45.173709+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=testsa23423.herokuapp.com request_id=e35b36c1-b34c-4856-9c4a-3fe1338732c8 fwd="187.109.234.254" dyno= connect= service= status=503 bytes= protocol=https
2021-02-10T18:50:46.131597+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=testsa23.herokuapp.com request_id=94d36057-2368-4c56-aea0-917262f9eeaa fwd="187.109.234.254" dyno= connect= service= status=503 bytes= protocol=https"

**Comment by eliasbenb** [comment]
> > Deployed just fine but when tried to visit the server, it crashed.
> > ![Screenshot](https://user-images.githubusercontent.com/18643014/106951505-dba77d00-6755-11eb-9cea-9377ea347387.jpg)
> 
> Same error :(
> 
> "2021-02-10T18:50:37.548981+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/configparser.py", line 1254, in __getitem__
> 2021-02-10T18:50:37.548981+00:00 app[web.1]:     raise KeyError(key)
> 2021-02-10T18:50:37.548981+00:00 app[web.1]: KeyError: 'cloudflare'
> 2021-02-10T18:50:37.549145+00:00 app[web.1]: [2021-02-10 18:50:37 +0000] [7] [INFO] Worker exiting (pid: 7)
> 2021-02-10T18:50:37.715928+00:00 app[web.1]: [2021-02-10 18:50:37 +0000] [4] [INFO] Shutting down: Master
> 2021-02-10T18:50:37.716038+00:00 app[web.1]: [2021-02-10 18:50:37 +0000] [4] [INFO] Reason: Worker failed to boot.
> 2021-02-10T18:50:37.785035+00:00 heroku[web.1]: Process exited with status 3
> 2021-02-10T18:50:37.869776+00:00 heroku[web.1]: State changed from up to crashed
> 2021-02-10T18:50:45.173709+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=testsa23423.herokuapp.com request_id=e35b36c1-b34c-4856-9c4a-3fe1338732c8 fwd="187.109.234.254" dyno= connect= service= status=503 bytes= protocol=https
> 2021-02-10T18:50:46.131597+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=testsa23.herokuapp.com request_id=94d36057-2368-4c56-aea0-917262f9eeaa fwd="187.109.234.254" dyno= connect= service= status=503 bytes= protocol=https"

This is a completely different issue

It's happening because I'm currently testing something. If you want to fix it, just add this line to the end of your LIBDRIVE_CONFIG:
`cloudflare=` just leave it empty

**Comment by ronioncloud** [comment]
> > > Deployed just fine but when tried to visit the server, it crashed.
> > > ![Screenshot](https://user-images.githubusercontent.com/18643014/106951505-dba77d00-6755-11eb-9cea-9377ea347387.jpg)
> > 
> > 
> > Same error :(
> > "2021-02-10T18:50:37.548981+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/configparser.py", line 1254, in **getitem**
> > 2021-02-10T18:50:37.548981+00:00 app[web.1]:     raise KeyError(key)
> > 2021-02-10T18:50:37.548981+00:00 app[web.1]: KeyError: 'cloudflare'
> > 2021-02-10T18:50:37.549145+00:00 app[web.1]: [2021-02-10 18:50:37 +0000] [7] [INFO] Worker exiting (pid: 7)
> > 2021-02-10T18:50:37.715928+00:00 app[web.1]: [2021-02-10 18:50:37 +0000] [4] [INFO] Shutting down: Master
> > 2021-02-10T18:50:37.716038+00:00 app[web.1]: [2021-02-10 18:50:37 +0000] [4] [INFO] Reason: Worker failed to boot.
> > 2021-02-10T18:50:37.785035+00:00 heroku[web.1]: Process exited with status 3
> > 2021-02-10T18:50:37.869776+00:00 heroku[web.1]: State changed from up to crashed
> > 2021-02-10T18:50:45.173709+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=testsa23423.herokuapp.com request_id=e35b36c1-b34c-4856-9c4a-3fe1338732c8 fwd="187.109.234.254" dyno= connect= service= status=503 bytes= protocol=https
> > 2021-02-10T18:50:46.131597+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=testsa23.herokuapp.com request_id=94d36057-2368-4c56-aea0-917262f9eeaa fwd="187.109.234.254" dyno= connect= service= status=503 bytes= protocol=https"
> 
> This is a completely different issue
> 
> It's happening because I'm currently testing something. If you want to fix it, just add this line to the end of your LIBDRIVE_CONFIG:
> `cloudflare=` just leave it empty

[log.txt](https://github.com/libDrive/libDrive/files/5960984/log.txt)

It looks like it's almost there.

**Comment by aditya-shri** [comment]
> Now a new error is happening after login.
> [logs.txt](https://github.com/libDrive/libDrive/files/5943774/logs.txt)
> 
Is this fixed?

**Comment by eliasbenb** [comment]
@aditya-shri @ronioncloud could you try redeploying with the newest updates

also, make sure you update your LIBDRIVE_CONFIG, the format has changed.

**Comment by aditya-shri** [comment]
> @aditya-shri @ronioncloud could you try redeploying with the newest updates
> 
> also, make sure you update your LIBDRIVE_CONFIG, the format has changed.

@eliasbenb Its giving timeout error
