### ISSUE TITLE
[BUG] I am unable to create credentials 

### ISSUE THREAD

**Issue by killerlearner** [libDrive/libDrive#20]
Hey, 
I am trying to create a lib drive in heroku. I also released my workflow, But I am unable to generate Authorization code, access token and refresh token. 
![Screenshot_2021-06-12-20-38-48-136_com android chrome](https://user-images.githubusercontent.com/67904798/121780696-24b58500-cbbf-11eb-93f4-a2d847a50d80.jpg)
And I already filled my google client id and secret id correctly but still I can't get cred, Do you know any solution. You can also contact me via tg @killerlearner. For fast response and help. And slso can you please tell what is the use of workflow I created 😅😅. 
 Thanks for help in advance.

**Comment by dishapatel010** [comment]
its not bug u should read how to [setup](https://github.com/libDrive/libDrive/wiki/Setup) properly.

**Comment by killerlearner** [comment]
> its not bug u should read how to [setup](https://github.com/libDrive/libDrive/wiki/Setup) properly.

Ahh I readded that but still didn't get the redirect uri is already setted and I can't set it back and mine api is also enable with google drive. Can you please tell what's the issue

**Comment by killerlearner** [comment]
Ok got it sorry I need to set redirect uri in my google api too. 
 Thanks for help
