### ISSUE TITLE
Showing late new upload files

### ISSUE THREAD

**Issue by Naim120** [libDrive/libDrive#21]
Ok i deployed it. But when i'm uploading new files index is showing it after 15-20 mins, not instantly. Any solution?

**Comment by dishapatel010** [comment]
Go to `yourapp.xyz/Settings`  & Click on rebuild metadata

**Comment by Naim120** [comment]
Ok i've done it. That will solve the late showing problem?
Thanks btw.

**Comment by dishapatel010** [comment]
Yes it will DO it after every time uploading new Files

**Comment by Naim120** [comment]
Okk thanks alot
