### ISSUE TITLE
My web didn't show anything

### ISSUE THREAD

**Issue by lesnolie** [libDrive/libDrive#23]
Hi there!
The libdrive looks amazing!
I hvae a question about my libdrive:
![image](https://user-images.githubusercontent.com/81410185/122735889-041db700-d2b2-11eb-8240-5e59072fc3d9.png)
I don't know why the web show nothing.
I check all step
can you help me?
I am very hope to receive your answer!
thank you!

**Comment by killerlearner** [comment]
Make sure you setted the folder id right while making config and also need to set name according to tmdb to get information about movie from that. In short check your folder id you setted in config is it right or not!

**Comment by eliasbenb** [comment]
> Hi there!
> The libdrive looks amazing!
> I hvae a question about my libdrive:
> ![image](https://user-images.githubusercontent.com/81410185/122735889-041db700-d2b2-11eb-8240-5e59072fc3d9.png)
> I don't know why the web show nothing.
> I check all step
> can you help me?
> I am very hope to receive your answer!
> thank you!

Did you just deploy the app? If so, it takes some time to load all the files in your drive, so wait a little bit. If there's still an issue, I'll need logs.

**Comment by askfriends** [comment]
Same here, i have just deployed 30mins ago and still no data is showing, i have put everything right as mentioned.

**Comment by lesnolie** [comment]
> Same here, i have just deployed 30mins ago and still no data is showing, i have put everything right as mentioned.

CHECK the googledrive api.
the https://config.libdrive.tk did not make me allow that api.
I allowed this api when I try to build locally

**Comment by lesnolie** [comment]
> > Hi there!
> > The libdrive looks amazing!
> > I hvae a question about my libdrive:
> > ![image](https://user-images.githubusercontent.com/81410185/122735889-041db700-d2b2-11eb-8240-5e59072fc3d9.png)
> > I don't know why the web show nothing.
> > I check all step
> > can you help me?
> > I am very hope to receive your answer!
> > thank you!
> 
> Did you just deploy the app? If so, it takes some time to load all the files in your drive, so wait a little bit. If there's still an issue, I'll need logs.

HI there.
Very thanks for your reply.
I have solved that question, cause there no goodrive api allowed.
 unfortunately there is a new question bothers me:

![image](https://user-images.githubusercontent.com/81410185/122917336-8086c780-d390-11eb-9b46-8f5cfb35a153.png)

![image](https://user-images.githubusercontent.com/81410185/122917398-909ea700-d390-11eb-99b7-06c949c4254f.png)

The movies and TV-show appear on the web but I couldn't watch online and download.
Whatever the heroapp or locally build.
But the UI is very beautiful.

**Comment by eliasbenb** [comment]
@lesnolie [My video won't load!](https://github.com/libDrive/libDrive/wiki/FAQ#my-video-wont-load)

**Comment by askfriends** [comment]
> > Same here, i have just deployed 30mins ago and still no data is showing, i have put everything right as mentioned.
> 
> CHECK the googledrive api.
> the https://config.libdrive.tk did not make me allow that api.
> I allowed this api when I try to build locally

Sorry i couldnt get you.
What do you mean to allow gdrive api?
where to do that? will you share screenshot plz?
thank you

**Comment by eliasbenb** [comment]
> > > Same here, i have just deployed 30mins ago and still no data is showing, i have put everything right as mentioned.
> > 
> > 
> > CHECK the googledrive api.
> > the https://config.libdrive.tk did not make me allow that api.
> > I allowed this api when I try to build locally
> 
> Sorry i couldnt get you.
> What do you mean to allow gdrive api?
> where to do that? will you share screenshot plz?
> thank you

https://developers.google.com/drive/api/v3/enable-drive-api

**Comment by askfriends** [comment]
> > > > Same here, i have just deployed 30mins ago and still no data is showing, i have put everything right as mentioned.
> > > 
> > > 
> > > CHECK the googledrive api.
> > > the https://config.libdrive.tk did not make me allow that api.
> > > I allowed this api when I try to build locally
> > 
> > 
> > Sorry i couldnt get you.
> > What do you mean to allow gdrive api?
> > where to do that? will you share screenshot plz?
> > thank you
> 
> https://developers.google.com/drive/api/v3/enable-drive-api

Its already enabled, here is the SS
https://tinyurl.com/yhscb2wm
