### ISSUE TITLE
[ENHANCEMENT] If u could add a contact button and a blog section

### ISSUE THREAD

**Issue by Naim120** [libDrive/libDrive#25]
2 feature ideas:

Feature 1: Add a contact button. If any problem appears in index, clicking on contact button will redirect the person to admin's social media account to contact him/her.

Feature 2: Add a little blog section, where only admin can write updates or blogs or post an youtube link or something like that. For example, "Loki Episode 3 is Added" could be written on the blog section, and time to time admin can write/update that.

If u could add these features, that would be really great. Thanks

**Comment by askfriends** [comment]
+1
and how about adding some html code before and after the video being played?

**Comment by eliasbenb** [comment]
No. libDrive is not an advertisement hub.
