### ISSUE TITLE
Doesn't show Movies or TV Series data after deploying

### ISSUE THREAD

**Issue by askfriends** [libDrive/libDrive#26]
I have followed the guide and deployed, everything seems to be right but it doesn't show any data on the web.
Here is the SS

![122735889-041db700-d2b2-11eb-8240-5e59072fc3d9 1](https://user-images.githubusercontent.com/2517219/123147964-1dbd2b00-d479-11eb-9e75-f7858ce85cce.png)

I have enabled gdrive api too
https://tinyurl.com/yhscb2wm

**Comment by eliasbenb** [comment]
On your server, could you go to this URL

`https://EXAMPLE.COM/api/v1/debug/metadata.json?secret=YOUR_SECRET_KEY`

It'll download a file name `metadata.json`, could you share it here?

**Comment by askfriends** [comment]
> `https://EXAMPLE.COM/api/v1/debug/metadata.json?secret=YOUR_SECRET_KEY`

here is the response i got
`{"code":404,"message":"The file/folder doesn't exist.","success":false}`
