### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by theRay1s** [libDrive/libDrive#27]
### Description

Sir When I add Cloudflare Worker link in config It show the the Error  When I Click on download 
I have added Screenshot for error 

So can u please Tell Me The Proper format Of adding Cloudflare working link in config

If applicable, add screenshots to help explain your problem

![Screenshot_2021-06-24-20-20-25-135_com android chrome](https://user-images.githubusercontent.com/54594678/123284341-ce830300-d529-11eb-916b-5b5d2b9ffe3b.jpg)

**Comment by eliasbenb** [comment]
I'm assuming you fixed the issue yourself because I went to your app and tested it, it works perfectly.
