### ISSUE TITLE
Can LibDrive Be deployed  to Qovery?

### ISSUE THREAD

**Issue by AmirulAndalib** [libDrive/libDrive#29]
### can lib-drive be deployed to qovery??     https://console.qovery.com/    if so please make it qovery deployable......

**Comment by eliasbenb** [comment]
It's against Qovery's TOS to deploy libDrive, so I won't be adding Qovery support.

**Comment by AmirulAndalib** [comment]
# then i suggest you shall remove Heroku Support too because its Against Heroku's TOS aswell and many are getting banned for deploying it after sometime

**Comment by eliasbenb** [comment]
> # then i suggest you shall remove Heroku Support too because its Against Heroku's TOS aswell and many are getting banned for deploying it after sometime

lol being salty about it isn't going to persuade me
