### ISSUE TITLE
[BUG]External Player Doesnt Work For TV Shows

### ISSUE THREAD

**Issue by montagne316** [libDrive/libDrive#30]
### Description

External player doesnt work with tv shows after the latest update

1. Go to 'https://libdrive.cf/view/1kcPOs2j73dK1MRsmLjwobrdAzBf7Prht
2. Click on 'External PLayer'
3. Try any player or u can use the copy url button and try loading the copied url it wont load anything

**Comment by eliasbenb** [comment]
https://github.com/libDrive/web/commit/e963f11228ccad222d90e50a17c1385ef0674259

fixed in this commit, you'll have to wait for the next update or build libDrive yourself though.

**Comment by montagne316** [comment]
Thanks ✌️
