### ISSUE TITLE
[BUG] Error 404: Not Found

### ISSUE THREAD

**Issue by LabbadBeta** [libDrive/libDrive#31]
Hello there ! I'm facing this bug in tv series section... Whenever i click on page it shows this error but movies section is working fine.. and i can search tv series from search and home page but tv series page always shows this error

ScreenShot:
![Screenshot_20210724-181113144](https://user-images.githubusercontent.com/87901566/126868753-ede71573-40f9-4f35-92da-029dc1f21384.jpg)

**Comment by eliasbenb** [comment]
I just went to your libDrive deployment `lib****x.herokuapp.com`
I'm not having the problem you're describing.

**Comment by LabbadBeta** [comment]
> I just went to your libDrive deployment `lib****x.herokuapp.com`
> I'm not having the problem you're describing.

Please open web series page and check bruh

**Comment by eliasbenb** [comment]
> > I just went to your libDrive deployment `lib****x.herokuapp.com`
> > I'm not having the problem you're describing.
> 
> Please open web series page and check bruh

Oh I understand what you mean now, you're talking about the browse page

The issue is in your `category_list` config, the `/` character is not allowed in the category name, removed it and it should be fixed.

**Comment by LabbadBeta** [comment]
> > > I just went to your libDrive deployment `lib****x.herokuapp.com`
> > > I'm not having the problem you're describing.
> > 
> > 
> > Please open web series page and check bruh
> 
> Oh I understand what you mean now, you're talking about the browse page
> 
> The issue is in your `category_list` config, the `/` character is not allowed in the category name, removed it and it should be fixed.

Okay bro trying that

**Comment by LabbadBeta** [comment]
> > > I just went to your libDrive deployment `lib****x.herokuapp.com`
> > > I'm not having the problem you're describing.
> > 
> > 
> > Please open web series page and check bruh
> 
> Oh I understand what you mean now, you're talking about the browse page
> 
> The issue is in your `category_list` config, the `/` character is not allowed in the category name, removed it and it should be fixed.

That problem solved thanks for help but now whenever i refresh the browse page an error pops up and says me to logout or retry that wasn't happened earlier

ScreenShot:
![Screenshot_20210724-182814187](https://user-images.githubusercontent.com/87901566/126869149-81890aaa-8f05-429c-9bf0-e6c17f77b686.jpg)

**Comment by eliasbenb** [comment]
@LabbadBeta the category name has a trailing space
chrome is automatically removing the space when you reload, which makes libDrive unable to find the category
remove the space at the end of the name and it'll be fixed.

**Comment by LabbadBeta** [comment]
> @LabbadBeta the category name has a trailing space
> chrome is automatically removing the space when you reload, which makes libDrive unable to find the category
> remove the space at the end of the name and it'll be fixed.

Thanks For Quick Help 🥰
