### ISSUE TITLE
Better cover images and anilist queries.

### ISSUE THREAD

**Issue by EverythingSuckz** [libDrive/libDrive#35]
Adding High Resolution Images along with better and short graphql queries for anilist API. Can I create a PR to the [server](https://github.com/libDrive/server) repository?
I've already tested it in [my instance](https://nothentai.tk) of libDrive.

**Comment by eliasbenb** [comment]
> Adding High Resolution Images along with better and short graphql queries for anilist API. Can I create a PR to the [server](https://github.com/libDrive/server) repository?
> I've already tested it in [my instance](https://nothentai.tk) of libDrive.

The lower resolution images was done on purpose, to have the page load faster and reduce bandwidth consumption. But I'm interested in the shorter GraphQL queries.

**Comment by EverythingSuckz** [comment]
> > Adding High Resolution Images along with better and short graphql queries for anilist API. Can I create a PR to the [server](https://github.com/libDrive/server) repository?
> > I've already tested it in [my instance](https://nothentai.tk) of libDrive.
> 
> The lower resolution images was done on purpose, to have the page load faster and reduce bandwidth consumption. But I'm interested in the shorter GraphQL queries.

Oh alright.. It's not that short but yeah.. it's the better way I suppose. Can I PR now?

**Comment by eliasbenb** [comment]
> > > Adding High Resolution Images along with better and short graphql queries for anilist API. Can I create a PR to the [server](https://github.com/libDrive/server) repository?
> > > I've already tested it in [my instance](https://nothentai.tk) of libDrive.
> > 
> > 
> > The lower resolution images was done on purpose, to have the page load faster and reduce bandwidth consumption. But I'm interested in the shorter GraphQL queries.
> 
> Oh alright.. It's not that short but yeah.. it's the better way I suppose. Can I create a PR now?

Sure

**Comment by eliasbenb** [comment]
Request has been merged.
https://github.com/libDrive/server/pull/4
