### ISSUE TITLE
[BUG] HTML tags in show description.

### ISSUE THREAD

**Issue by EverythingSuckz** [libDrive/libDrive#36]
### Description

In anilist.. The API return the show description along with `<br>` html tag even if we set `(asHtml: false)` so it would be better if the tags were removed

### To Reproduce

1. Visit any folders in libDrive instances having anilist as true and check the show description,  for example [here](https://libdrive.cf/view/1aE1BKJZrD9ypVDYlZ56ZDrXeV0KToNhP)

### Runtime

- Deployment method: private server
- Device: browser
- libDrive version: v1.3.10

### Additional information

I've fixed it on my instance [here](https://nothentai.tk/view/12e4qqHtA4v6AJMTyukvZQqzoyOxP2dCT).
I've just added the following function and it works.
```python3
def cleanHtml(with_html):
    if with_html:# avoid TypeError if the args are NoneType
        cleanr = re.compile('<.*?>')
        cleantext = re.sub(cleanr, '', with_html)
        return cleantext
```

**Comment by eliasbenb** [comment]
https://github.com/libDrive/server/commit/c27703abbbc91f2da5a74ddd6877bcf08559df1e

Done. Thank you for your contribution!
