### ISSUE TITLE
Change Video Quality

### ISSUE THREAD

**Issue by nikhil7759** [libDrive/libDrive#45]
Hey there!
Can you please tell me how can i change video quality?
It's not working!!

**Comment by flixverse** [comment]
You need to make the cloudflare worker and it's url in the config and set transcoded as true

**Comment by nikhil7759** [comment]
![Screenshot 2021-08-17 002940](https://user-images.githubusercontent.com/81584740/129615954-b26e7de8-d6a6-4594-8a74-f514c40001ca.png)
Please help

**Comment by LumberJack69** [comment]
set "transcoding = true" instead of false in your code

**Comment by nikhil7759** [comment]
> set "transcoding = true" instead of false in your code

![Screenshot 2021-08-18 175045](https://user-images.githubusercontent.com/81584740/129897269-7835dc8f-bc11-4af0-b690-f8cf9696b556.png)
already done

**Comment by eliasbenb** [comment]
> > set "transcoding = true" instead of false in your code
> 
> ![Screenshot 2021-08-18 175045](https://user-images.githubusercontent.com/81584740/129897269-7835dc8f-bc11-4af0-b690-f8cf9696b556.png)
> already done

don't edit the config manually, use https://config.libdrive.tk

`true` and `false` shouldn't be in quoations.

Also read this.
![image](https://user-images.githubusercontent.com/54410649/131260213-56915367-fd50-42d4-ad3a-cf74cb90b111.png)
