### ISSUE TITLE
How do I deploy to heroku using the cli local

### ISSUE THREAD

**Issue by abdiasriver** [libDrive/libDrive#46]
How do I deploy heroku when I have cloned the ; heroku, libdrive, server & web repository?
- I create my app using cli of heroku locally
Could someone help?
Since it is not possible to download the heroku code

**Comment by MrNoobyDev** [comment]
Thats Not Enhancement Issue. Join the Support Group

**Comment by eliasbenb** [comment]
```
git clone https://github.com/libDrive/heroku
heroku git:remote -a APP_NAME
heroku stack:set container
git push heroku main
```
