### ISSUE TITLE
No sound on chrome [BUG]

### ISSUE THREAD

**Issue by abdiasriver** [libDrive/libDrive#47]
### Description

The sound on chrome isnt work

### To Reproduce

Only on chrome , not on edge or firefox

### Additional information
I know, i read the wiki , but why only chrome, most people use that

**Comment by eliasbenb** [comment]
It's normal for some audio to not work on the browser, especially chrome.

It's because of copyright issues. Different companies own the rights to different audio codecs, chrome is unwilling to pay for the rights to use those codecs, so it's not supported.
