### ISSUE TITLE
[ENHANCEMENT] option to update mismatched shows and movies

### ISSUE THREAD

**Issue by SJ50** [libDrive/libDrive#49]
### Outline of feature request

Please include option to update mismatched shows and movies

### Reason

I got couple of shows which are mismatched which I like to fix.

**Comment by SpeedyIndeedy** [comment]
What do you mean by update? Give example

**Comment by MrNoobyDev** [comment]
Bro Explain Your Issue Clearly

**Comment by SJ50** [comment]
For example, I have this series [Babies](https://www.themoviedb.org/tv/99103-babies) but in libdrive it got matched with [muppet babies](https://www.themoviedb.org/tv/77410-muppet-babies) which I want to fix.

**Comment by eliasbenb** [comment]
Good suggestion, but won't be worked on any time soon.

**Comment by SJ50** [comment]
@eliasbenb Whenever time permits, not in hurry.
