### ISSUE TITLE
[BUG]Heroku Error

### ISSUE THREAD

**Issue by leonard4546** [libDrive/libDrive#5]
I was trying to deploy this on heroku but facing some issue. added all variables. 
[ooof-logs-1612980583593.txt](https://github.com/libDrive/libDrive/files/5960446/ooof-logs-1612980583593.txt)

**Comment by eliasbenb** [comment]
If you still have this issue, can you please try deploying the new updated version.
If you still have an issue, please send the new logs.

**Comment by leonard4546** [comment]
> Can you please try deploying the new updated version.
> If you still have an issue, please send the new logs.

New version working.
