### ISSUE TITLE
[BUG] Wiki

### ISSUE THREAD

**Issue by SpeedyIndeedy** [libDrive/libDrive#52]
There is a small fix needed in wiki's Config page after [Remove No Poster](https://github.com/libDrive/libDrive/wiki/Config#remove_no_poster). Just a small issue.

**Comment by eliasbenb** [comment]
That's a pretty big issue actually. Should be fixed now in this commit.

https://github.com/libDrive/libDrive/wiki/Config/bbad5143eabf2085ed81da5d28d32fff4ad1cd4d

**Comment by SpeedyIndeedy** [comment]
Dude 😑😑
