### ISSUE TITLE
[BUG] Not fetching metadata

### ISSUE THREAD

**Issue by sp003** [libDrive/libDrive#6]
### Description

Not fetching metadata of all the content . I have added some Bollywood movies folder but looks like it only fetches few  . Other appear as only hyperlink , no description, icon of broken images , which appears very bad.

### To Reproduce

1. Add config with all spaces filled(including cf proxy)
2. Deploy
3. Login
4. Goto home

### Expected behavior

All content metadata should be fetched . Or you can add other scraper along with tmdb .

### Logs

[logs.txt](https://github.com/libDrive/libDrive/files/5982108/logs.txt)

### Screenshots

```
https://i.imgur.com/1BWhpuU.jpg
https://i.imgur.com/aMzEAeh.jpg
https://i.imgur.com/MLbK6QL.jpg
https://i.imgur.com/dUxUwkV.jpg
```

### Runtime

- Deployment method: Heroku
- Device: chrome : android 10: Pocophone F1
- libDrive version: latest 15/02

**Comment by eliasbenb** [comment]
Please have a look at the wiki <https://github.com/libDrive/libDrive/wiki/Structure>

libDrive only supports specific naming conventions.  This may be improved in the future, but for now those are the requirements.

**Comment by eliasbenb** [comment]
Since there has been no reply in 5 days, I'll assume OP has no more questions and close the issue.
