### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Rocky2242** [libDrive/libDrive#7]
### Error!
Something went wrong while communicating with the backend!
![Screenshot (33)](https://user-images.githubusercontent.com/57870860/108019975-5e2b1900-7041-11eb-9c95-ba1d4981ead2.png)

**Comment by eliasbenb** [comment]
How did you get to that page? Did you manually enter that URL? Because that's not how libDrive URLs work

**Comment by eliasbenb** [comment]
Since there was no reply in 4 days, I'll close the issue.
