### ISSUE TITLE
Feature Request - Limiting Access to Certain parts of library for Some Users

### ISSUE THREAD

**Issue by DeadCore-123** [libDrive/libDrive#8]
### Outline of feature request

A Feature Request to limit access of Users to only a A Section of Available content 
Like User 1 only has Access to Movies 
User 2 has only access to cartoon 
User 3 has the master access to all of them 

Something like that

### Reason

I am sharing the LibDrive with my little brother and i don't want him to access certain piece of content . I only want him to access the Cartoon Section that I made for Cartoons and Anime for him to watch

**Comment by eliasbenb** [comment]
I just pushed out a commit which implements this feature.
To enable it, you need to add a `whitelist` field to the account list conifg
```
{
	"account_list": [
		{
			"username": "USER_1",
			"password": "PASS_1",
			"pic": "https://i.ibb.co/3WNmpb0/Logo.png",
			"auth": "z1w5o1na3v843um9ktr2km9et0shx1ebgh4dmfgorth6ivao71",
			"whitelist": [
				"FOLDER_ID_1",
				"FOLDER_ID_2"
			]
		}
	]
}
```
The field consists of a list of folder IDs which the user can access. So an empty `whitelist` means the user can't access anything. If you want the user to access everything, just remove the `whitelist` field.

This commit has not been released yet, so you will need to build it on your own, or wait.

https://github.com/libDrive/backend/commit/c8112fd496717baf97443c96596a720f7d21421b

**Comment by DeadCore-123** [comment]
Thanks Dude . Thank you very much
